# -*- coding: utf-8 -*-
"""ML+Deep_Learning_Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1zMrSaO_eC2Ni1KHiMyEmrH_RGwMyiOup
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder , OneHotEncoder
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score,mean_absolute_error,mean_squared_error

# load dataset
data = pd.read_csv('/content/cropdata_updated.csv')
# data analysis
data.head()
data.isnull().sum()
data.shape
data.info()
data.describe()

# data Visualization
numerical_columns = ['MOI','temp','result','humidity']
catergorial_columns = ['crop ID','soil_type','Seedling Stage']
for col in numerical_columns :
  plt.figure(figsize=(10,5))
  sns.histplot(x = data[col])
  plt.xticks(rotation=90)
  plt.show()

for col in  catergorial_columns:
  sns.countplot(x=data[col])
  plt.xticks(rotation=90)
  plt.show()

sns.pairplot(data)
plt.show()

sns.heatmap(data.corr(numeric_only=True),annot=True)
plt.show()

sns.scatterplot(x=data['temp'],y=data['result'])
plt.show()

# Feature engineering
data.columns

data['Fungal_Risk'] = data['MOI'] * data['temp']
data['Fungal_Risk']
data['Sauna Effect'] = data['temp'] * data['humidity']
data['Sauna Effect']

from sklearn.pipeline import Pipeline
from sklearn.ensemble import RandomForestClassifier
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler, OneHotEncoder

# Re-split data to ensure engineered features are included in x_train/x_test
x = data.drop('result', axis=1)
y = data['result']
x_train , x_test , y_train , y_test = train_test_split(x, y, test_size=0.2, random_state=42)

# Define feature columns based on x_train
numerical_features = ['MOI','temp','humidity','Fungal_Risk','Sauna Effect']
categorical_features = ['crop ID', 'soil_type', 'Seedling Stage'] # Treat these as categorical for OneHotEncoder

# Preprocessing Pipelines
numerical_transformer = Pipeline(steps=[
    ('scaler', StandardScaler())
])

categorical_transformer = Pipeline(steps=[
    ('onehot', OneHotEncoder(handle_unknown='ignore'))
])

# Create a preprocessor using ColumnTransformer
preprocessor = ColumnTransformer(
    transformers=[
        ('num', numerical_transformer, numerical_features),
        ('cat', categorical_transformer, categorical_features)
    ],
    remainder='passthrough' # Keep any other columns not explicitly transformed
)

# Define the full pipeline: preprocessor + model
full_pipeline = Pipeline(steps=[
    ('preprocessor', preprocessor),
    ('regressor', RandomForestClassifier())
])

# Fit the full pipeline on training data
full_pipeline.fit(x_train,y_train)

test_accuracy = full_pipeline.predict(x_test)
train_accuracy = full_pipeline.predict(x_train)
r2_testing = r2_score(y_test,test_accuracy)
r2_training = r2_score(y_train,train_accuracy)
mae = mean_absolute_error(y_test,test_accuracy)

print(f"R2 Score for Testing Data: {r2_testing}")
print(f"R2 Score for Training Data: {r2_training}")
print(f"Mean Absolute Error: {mae}")

from sklearn.model_selection import RandomizedSearchCV

para_grid = {
    'regressor__n_estimators': [100, 200, 300],
    'regressor__max_depth': [10, 20, 30],
    'regressor__min_samples_split': [2, 5, 10],
    'regressor__min_samples_leaf': [1,2,4]
}

random_Search = RandomizedSearchCV(
    estimator=full_pipeline,
    param_distributions=para_grid,
    n_iter=10,
    cv=5,
    verbose=2,
    random_state=42,
)

random_Search.fit(x_train, y_train)

import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Dropout
from tensorflow.keras.utils import to_categorical

# Preprocess the training and test features using the already fitted preprocessor
X_train_processed_ann = preprocessor.transform(x_train)
X_test_processed_ann = preprocessor.transform(x_test) # Use x_test here for features

# Encode target variables
y_train_encoded = to_categorical(y_train, num_classes=3)
y_test_encoded = to_categorical(y_test, num_classes=3) # Encode y_test as well

model = Sequential([
    Dense(16,activation='relu',input_shape=(X_train_processed_ann.shape[1],)), # Use processed shape
    Dense(8,activation='relu'),
    Dense(3,activation='softmax')
])

model.compile(optimizer='adam',loss='categorical_crossentropy',metrics=['accuracy'])

history = model.fit(X_train_processed_ann, y_train_encoded, # Use processed features and encoded target
                    validation_data=(X_test_processed_ann, y_test_encoded), # Correct validation data
                    epochs=30 , batch_size=32)

plt.plot(history.history['accuracy'])
plt.plot(history.history['val_accuracy'])

plt.legend(['Train', 'Validation'], loc='upper left')
